/**
 * Custom Style Dictionary formats for Web (CSS custom properties + JSON).
 */

import type { Format, FormatFnArguments } from 'style-dictionary/types';
import type { TypographyTokenValue } from './types.js';

function kebabCase(path: string[]): string {
  return path.join('-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase();
}

function camelCase(path: string[]): string {
  return path
    .map((p, i) => (i === 0 ? p : p.charAt(0).toUpperCase() + p.slice(1)))
    .join('');
}

/**
 * css/colorVariables – CSS custom properties for primitive colors.
 */
export const cssColorVariables: Format = {
  name: 'css/colorVariables',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter((t) => t.$type === 'color');

    const lines = tokens.map((token) => {
      const name = kebabCase(token.path);
      const hex = (token.$value || token.value) as string;
      return `  --wds-${name}: ${hex};`;
    });

    return [
      '/* Generated by World Design System – do not edit manually */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * css/themeVariables – CSS custom properties for theme colors (semantic tier
 * + component tier). Both tiers land in the same per-theme stylesheet, keyed
 * by `--wds-{kebabName}` using the path minus the tier prefix so existing
 * consumers keep using `--wds-action-primary`, `--wds-surface-primary`, etc.
 */
export const cssThemeVariables: Format = {
  name: 'css/themeVariables',
  format: ({ dictionary, options }: FormatFnArguments) => {
    const selector = (options.selector as string) || ':root';
    const tokens = dictionary.allTokens.filter(
      (t) =>
        t.$type === 'color' &&
        (t.path[0] === 'semantic' || t.path[0] === 'component'),
    );

    const lines = tokens.map((token) => {
      const name = kebabCase(token.path.slice(1));
      const hex = (token.$value || token.value) as string;
      return `  --wds-${name}: ${hex};`;
    });

    return [
      '/* Generated by World Design System – do not edit manually */',
      `${selector} {`,
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * css/typography – CSS custom properties for typography tokens.
 */
export const cssTypography: Format = {
  name: 'css/typography',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'typography',
    );

    const lines = tokens.flatMap((token) => {
      const name = token.path[token.path.length - 1];
      const v = (token.$value || token.value) as TypographyTokenValue;
      const lineHeight = (v.fontSize * v.lineHeightMultiplier).toFixed(1);
      return [
        `  --wds-typography-${name}-font-size: ${v.fontSize}px;`,
        `  --wds-typography-${name}-font-weight: ${v.fontWeight};`,
        `  --wds-typography-${name}-letter-spacing: ${v.letterSpacing}em;`,
        `  --wds-typography-${name}-line-height: ${lineHeight}px;`,
      ];
    });

    return [
      '/* Generated by World Design System – do not edit manually */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * css/spacing – CSS custom properties for spacing tokens.
 */
export const cssSpacing: Format = {
  name: 'css/spacing',
  format: ({ dictionary }: FormatFnArguments) => {
    const tokens = dictionary.allTokens.filter(
      (t) => t.$type === 'dimension' && t.path[0] === 'spacing',
    );

    const lines = tokens.map((token) => {
      const name = token.path[token.path.length - 1];
      const v = (token.$value ?? token.value) as number;
      return `  --wds-spacing-${name}: ${v}px;`;
    });

    return [
      '/* Generated by World Design System – do not edit manually */',
      ':root {',
      ...lines,
      '}',
      '',
    ].join('\n');
  },
};

/**
 * json/flat – Flat JSON object for all tokens, used by the website.
 */
export const jsonFlat: Format = {
  name: 'json/flat',
  format: ({ dictionary }: FormatFnArguments) => {
    const result: Record<string, unknown> = {};

    for (const token of dictionary.allTokens) {
      const key = camelCase(token.path);
      const value = token.$value ?? token.value;

      if (token.$type === 'color') {
        result[key] = value;
      } else if (token.$type === 'typography') {
        const v = value as TypographyTokenValue;
        result[key] = {
          fontSize: v.fontSize,
          fontWeight: v.fontWeight,
          letterSpacing: v.letterSpacing,
          lineHeightMultiplier: v.lineHeightMultiplier,
        };
      } else if (token.$type === 'dimension') {
        result[key] = value;
      }
    }

    return JSON.stringify(result, null, 2) + '\n';
  },
};
